### ISSUE TITLE
DockerComposeEnvironment Not Working in Bazel Test (Container not starting)

### ISSUE THREAD

**Issue by flolu** [testcontainers/testcontainers-node#113]
I have a simple docker-compose.json file
```json
{
  "version": "3",
  "services": {
    "gateway": {
      "image": "node:lts-alpine",
      "container_name": "gateway",
      "command": "yarn run ts-node-dev gateway",
      "working_dir": "/",
      "volumes": [
        "./package.json:/package.json",
        "./tsconfig.json:/tsconfig.json",
        "./node_modules:/node_modules",
        "./gateway:/gateway"
      ],
      "ports": ["3000:3000"]
    }
  }
}

```

and a small Typescript test:
```typescript
import * as path from 'path'
import {DockerComposeEnvironment} from 'testcontainers'
import axios from 'axios'

import message from './message'

describe('integration test', () => {
  it('starts gateway', async () => {
    const filepath = path.join(__dirname, '../')
    const filename = 'docker-compose.json'
    const env = await new DockerComposeEnvironment(filepath, filename).withBuild().up()
    // make sure server is started
    await wait(3000)
    const res = await axios.get('http://localhost:3000')
    expect(res.data.toString()).toEqual(message)
    await env.down()
  })
})

function wait(ms: number) {
  return new Promise(res => {
    setTimeout(() => res(), ms)
  })
}
```

Running the test directly with Jasmine works fine.
But running the test with Bazel doesn't work.

The http request fails with `Error: connect ECONNREFUSED 127.0.0.1:3000�[0m`
So it seems as if the container cannot start or is not starting properly.

**Minimal reproduction: https://github.com/flolu/bazel-testcontainers-repro**

**Comment by cristianrgreco** [comment]
Hi @flolu, I don't know anything about Blaze.. why could it be that the test fails when using their runner?

**Comment by flolu** [comment]
@cristianrgreco Honestly, I have no idea.
Maybe @alexeagle or @gregmagolan has any ideas about this one?

**Comment by cristianrgreco** [comment]
@flolu I'm unable to run the repro, I get:

```
Failures:
1) integration test starts gateway
  Message:
    Error: Creating network "bazel_testcontainers_repro_default" with the default driver
    Pulling gateway (node:lts-alpine)...
    Get https://registry-1.docker.io/v2/library/node/manifests/lts-alpine: unauthorized: incorrect username or password
  Stack:
    Error: Creating network "bazel_testcontainers_repro_default" with the default driver
    Pulling gateway (node:lts-alpine)...
    Get https://registry-1.docker.io/v2/library/node/manifests/lts-alpine: unauthorized: incorrect username or password
        at DockerComposeEnvironment.<anonymous> (node_modules/testcontainers/dist/docker-compose-environment.js:105:23)
        at <Jasmine>
        at rejected (node_modules/testcontainers/dist/docker-compose-environment.js:25:65)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)

1 spec, 1 failure
Finished in 2.521 seconds
```

**Comment by flolu** [comment]
@cristianrgreco Interesting... it works on my side. It seems to have trouble pulling the `node:lts-alpine` image. Do you have Docker installed on your system?

**Comment by cristianrgreco** [comment]
@flolu Yes

**Comment by cristianrgreco** [comment]
@flolu i've raised a PR against your repro, there's no issue with testcontainers, just incorrect usage: https://github.com/flolu/bazel-testcontainers-repro/pull/1
