### ISSUE TITLE
Error: Cannot get container "[...]" as it is not running - when using gitlab-ci, dind and docker-compose

### ISSUE THREAD

**Issue by FrederikP** [testcontainers/testcontainers-node#116]
Hi,

I have a weird issue that only happens on our CI system and I'm unable to work around it.
Everything works fine locally.

DOCKER_HOST is set to the docker service specified in our gitlab ci job config. The setup works for testcontainers java in a different project.

This is the error that is thrown in every CI build:
```
Error: Cannot get container "[...]" as it is not running
    at StartedDockerComposeEnvironment.getContainer ([...]/node_modules/testcontainers/dist/docker-compose-environment.js:172:19)
    at exports.default ([...]/test/setup.ts:10:35)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async [...]/node_modules/@jest/core/build/runGlobalHook.js:82:11
    at async waitForPromiseWithCleanup ([...]/node_modules/@jest/transform/build/ScriptTransformer.js:206:5)
    at async [...]/node_modules/@jest/core/build/runGlobalHook.js:72:9
    at async pEachSeries ([...]/node_modules/p-each-series/index.js:8:3)
    at async _default ([...]/node_modules/@jest/core/build/runGlobalHook.js:58:5)
    at async runJest ([...]/node_modules/@jest/core/build/runJest.js:345:5)
    at async _run10000 ([...]/node_modules/@jest/core/build/cli/index.js:416:7)
```

At first I suspected that maybe the CI docker-compose call doesn't wait long enough for the container to really be up. So what I tried to work around this issue was just calling:
```
    - docker-compose -f test/docker-compose.yml up -d
    - sleep 10
```
before even running my e2e tests. The container is definitely up and running. But the test setup fails with the same error shown above.

Am I doing something wrong, or is this some sort of a bug. If it may be a bug, is there a different way I could try to work around it?

Thanks for taking a look.

**Comment by FrederikP** [comment]
I extracted the essential parts needed to reproduce the issue and created a gitlab project:

https://gitlab.com/FrederikP/reproduce-testcontainers-issue

It includes gitlab-ci config, testcontainers calls.

You can see the error here: https://gitlab.com/FrederikP/reproduce-testcontainers-issue/-/jobs/728802168

```
    Error: Cannot get container "reproduce-testcontainers-issue_postgres_1" as it is not running
        at StartedDockerComposeEnvironment.getContainer (/builds/FrederikP/reproduce-testcontainers-issue/node_modules/testcontainers/dist/docker-compose-environment.js:172:19)
        at /builds/FrederikP/reproduce-testcontainers-issue/example.test.ts:20:35
        at step (/builds/FrederikP/reproduce-testcontainers-issue/example.test.ts:33:23)
        at Object.next (/builds/FrederikP/reproduce-testcontainers-issue/example.test.ts:14:53)
        at fulfilled (/builds/FrederikP/reproduce-testcontainers-issue/example.test.ts:5:58)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at process.uncaught (node_modules/jest-jasmine2/build/jasmine/Env.js:249:21)
```

Locally the test is green for me and docker-compose works without issues.

If you want to try, just clone the repository and run

```
npm install
npm test
```

Of course node, npm, docker, docker-compose need to be available.

**Comment by cristianrgreco** [comment]
Hi @FrederikP, are you able to run a `docker ps` after testcontainers starts the container? 

I'd like to see if the problem is either:
1. The container is not starting
2. The container has started with a name testcontainers doesn't recognise

**Comment by FrederikP** [comment]
Hi @cristianrgreco ,
sure. I added it between `up()` and `getContainer()`. This is the result:

https://gitlab.com/FrederikP/reproduce-testcontainers-issue/-/jobs/734440586

Relevant lines:

```
console.log
    docker ps:
     CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                  PORTS                     NAMES
    0f28b7540257        postgres:latest     "docker-entrypoint.s…"   3 seconds ago       Up Less than a second   0.0.0.0:32768->5432/tcp   issue_reproduction_postgres
      at example.test.ts:26:13
  console.error
    Unhandled error
      at process.uncaught (node_modules/jest-jasmine2/build/jasmine/Env.js:248:21)
  console.error
    Error: Cannot get container "issue_reproduction_postgres" as it is not running
        at StartedDockerComposeEnvironment.getContainer (/builds/FrederikP/reproduce-testcontainers-issue/node_modules/testcontainers/dist/docker-compose-environment.js:172:19)
        at /builds/FrederikP/reproduce-testcontainers-issue/example.test.ts:28:35
        at step (/builds/FrederikP/reproduce-testcontainers-issue/example.test.ts:52:23)
        at Object.next (/builds/FrederikP/reproduce-testcontainers-issue/example.test.ts:33:53)
        at fulfilled (/builds/FrederikP/reproduce-testcontainers-issue/example.test.ts:24:58)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at process.uncaught (node_modules/jest-jasmine2/build/jasmine/Env.js:249:21)
```

> 1. The container is not starting
> 2. The container has started with a name testcontainers doesn't recognise

To me it looks like both these things don't apply. The container started and the name is the same.

**Comment by cristianrgreco** [comment]
Thanks @FrederikP that's very useful.

In that case it seems testcontainers didn't find the container. It does this by listing all running containers and filtering on their labels to find the ones started by docker-compose (https://github.com/testcontainers/testcontainers-node/blob/master/src/docker-compose-environment.ts#L110).

Are you able to run a `docker inspect` on the `issue_reproduction_postgres` container when it's running and share the output?

**Comment by FrederikP** [comment]
Okay, I did that. See: https://gitlab.com/FrederikP/reproduce-testcontainers-issue/-/jobs/735040601

Most relevant: 

```
__dirname: /builds/FrederikP/reproduce-testcontainers-issue
```

```
                "Labels": {
                    "com.docker.compose.config-hash": "ea20ab1bbc923d6b565b7be6f3bf4f524b451773890f0d06fba9d15077e89d9d",
                    "com.docker.compose.container-number": "1",
                    "com.docker.compose.oneoff": "False",
                    "com.docker.compose.project": "reproduce-testcontainers-issue",
                    "com.docker.compose.service": "postgres",
                    "com.docker.compose.version": "1.24.1"
                }
```

If you have a gitlab account you can also fork the repo and adjust console.logs yourself. There is no special setup involved. It's using gitlabs standard CI runners, etc. Might be quicker than waiting for me to react. But I'm happy to do so as well.

**Comment by cristianrgreco** [comment]
@FrederikP This is now fixed in 3.4.4 https://gitlab.com/cristianrgreco/reproduce-testcontainers-issue/-/jobs/735098479. Thanks for raising the issue and having such a good repro 🙂 If all's well please close the issue

**Comment by FrederikP** [comment]
Nice. Yes it is fixed for my more complex real-life project as well. Thanks a ton for the fix and quick reaction

**Comment by cristianrgreco** [comment]
Hi @FrederikP, just letting you know that since releasing 4.0.0 I have found another issue with docker-compose in gitlab, it's different to this one but just FYI don't upgrade just yet. I am working on it and will update here once resolved

**Comment by FrederikP** [comment]
Thank you very much. Very considerate!
Sep 19, 2020 11:51:29 Cristian Greco <notifications@github.com>:

**Comment by cristianrgreco** [comment]
This is working again as of 4.0.9 🙂
