### ISSUE TITLE
How can I map port into service port (Rabbitmq) - instead just expose the default

### ISSUE THREAD

**Issue by johnico** [testcontainers/testcontainers-node#148]
I would like to create a rabbitContaienr  . like:

```
 await new GenericContainer('rabbitmq:3').withExposedPorts('2222:5672')
      .start()
```

but today is not an option 
if I have multiple services that run the test on the same machine, i want that each of the tests will create a rabbit container and will expose a random port

so how can I manage to achieve smth like:

```
ports 
 -  '12345':5672
```

thanks

**Comment by cristianrgreco** [comment]
hi @johnico, having each container expose a random port is the default behaviour, did you see the README?

```javascript
const container = await new GenericContainer('rabbitmq:3')
  .withExposedPorts(5672)
  .start();

const mappedPort = container.getMappedPort(5432); // the mapped port is random
```

so if each test starts its own container, each will have a rabbit listening on a random port

**Comment by johnico** [comment]
hi 
@cristianrgreco  thanks 

how can I define multiple ports? 

now I am getting

```
{ Error: (HTTP code 400) unexpected - invalid reference format 
    at (.../node_modules/docker-modem/lib/modem.js:301:17
    at getCause ((.../node_modules/docker-modem/lib/modem.js:331:7)
    at Modem.buildPayload (.../node_modules/docker-modem/lib/modem.js:300:5)
    at IncomingMessage.<anonymous> ((.../node_modules/docker-modem/lib/modem.js:275:14)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  reason: undefined,
  statusCode: 400,
  json: { message: 'invalid reference format' } }
```

my code:

```
    container = await new GenericContainer('rabbitmq:3')
      .withExposedPorts(5672)
      .start();
```

**Comment by johnico** [comment]
@cristianrgreco  thanks a lot 

how can I declare multiple ports? , is it by order?

**Comment by cristianrgreco** [comment]
@johnico with varargs: `.withExposedPorts(80, 443)`, order doesn't matter
