### ISSUE TITLE
Kafka example fails with Zookeeper panic "Unable to create data directory"

### ISSUE THREAD

**Issue by jonathankeebler** [testcontainers/testcontainers-node#210]
MacOSX 11.3.1
Node 12.x

I copied/pasted the first "built-in Zookeeper" example from https://github.com/testcontainers/testcontainers-node/tree/master/src/modules/kafka. The docker instances are created, but the cp-zookeeper instance fails with the following:
````
===> User
uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
===> Configuring ...
===> Running preflight checks ... 
===> Check if /var/lib/zookeeper/data is writable ...
===> Check if /var/lib/zookeeper/log is writable ...
===> Launching ... 
===> Launching zookeeper ... 
[2021-05-10 15:33:21,279] INFO Reading configuration from: /etc/kafka/zookeeper.properties (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-05-10 15:33:21,301] INFO clientPortAddress is 0.0.0.0:48471 (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-05-10 15:33:21,301] INFO secureClientPort is not set (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-05-10 15:33:21,306] INFO autopurge.snapRetainCount set to 3 (org.apache.zookeeper.server.DatadirCleanupManager)
[2021-05-10 15:33:21,306] INFO autopurge.purgeInterval set to 0 (org.apache.zookeeper.server.DatadirCleanupManager)
[2021-05-10 15:33:21,307] INFO Purge task is not scheduled. (org.apache.zookeeper.server.DatadirCleanupManager)
[2021-05-10 15:33:21,307] WARN Either no config or no quorum defined in config, running  in standalone mode (org.apache.zookeeper.server.quorum.QuorumPeerMain)
[2021-05-10 15:33:21,317] INFO Log4j 1.2 jmx support found and enabled. (org.apache.zookeeper.jmx.ManagedUtil)
[2021-05-10 15:33:21,336] INFO Reading configuration from: /etc/kafka/zookeeper.properties (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-05-10 15:33:21,337] INFO clientPortAddress is 0.0.0.0:48471 (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-05-10 15:33:21,337] INFO secureClientPort is not set (org.apache.zookeeper.server.quorum.QuorumPeerConfig)
[2021-05-10 15:33:21,338] INFO Starting server (org.apache.zookeeper.server.ZooKeeperServerMain)
[2021-05-10 15:33:21,343] INFO zookeeper.snapshot.trust.empty : false (org.apache.zookeeper.server.persistence.FileTxnSnapLog)
[2021-05-10 15:33:21,344] ERROR Unable to access datadir, exiting abnormally (org.apache.zookeeper.server.ZooKeeperServerMain)
org.apache.zookeeper.server.persistence.FileTxnSnapLog$DatadirException: Unable to create data directory /var/lib/zookeeper/log/version-2
	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.<init>(FileTxnSnapLog.java:127)
	at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:125)
	at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:107)
	at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:65)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:128)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
Unable to access datadir, exiting abnormally

**Comment by cristianrgreco** [comment]
Hi @jonathankeebler, these are the tests that are run for the kafka module: https://github.com/testcontainers/testcontainers-node/blob/master/src/modules/kafka/kafka-container.test.ts

Are you able to use them to get a working example using the built-in ZK?

**Comment by jonathankeebler** [comment]
FYI the generic container tests are passing (except for the private repos which I assume were just a permissions problem):
<img width="965" alt="Screen Shot 2021-05-11 at 11 03 20 AM" src="https://user-images.githubusercontent.com/4992815/117838662-87c29d80-b248-11eb-8366-936fbc84d848.png">

**Comment by jonathankeebler** [comment]
I got it working when I specified the volumes on a custom Zookeeper:
```
const { GenericContainer, KafkaContainer, Network } = require("testcontainers");

        const ZOO_KEEPER_HOST = "zookeeper";
        const ZOO_KEEPER_PORT = 2181;

        const network = await new Network().start();

        const zooKeeperContainer = await new GenericContainer("confluentinc/cp-zookeeper:latest")
            .withName(ZOO_KEEPER_HOST)
            .withEnv("ZOOKEEPER_CLIENT_PORT", ZOO_KEEPER_PORT.toString())
            .withNetworkMode(network.getName())
            .withBindMount("/Users/jonathan/docker/log", "/var/lib/zookeeper/log/version-2")
            .withBindMount("/Users/jonathan/docker/data", "/var/lib/zookeeper/data/version-2")
            .start();

        const kafkaContainer = await new KafkaContainer()
            .withNetworkMode(network.getName())
            .withZooKeeper(ZOO_KEEPER_HOST, ZOO_KEEPER_PORT)
            .withExposedPorts(9093)
            .start()

**Comment by cristianrgreco** [comment]
Looks like there was a major version change from `5.4.4` to `6.1.1`, could you try `5.4.4`? If that works then we can hardcode the version in the example

**Comment by jonathankeebler** [comment]
I got a `Error: (HTTP code 404) no such container - No such image: confluentinc/cp-zookeeper:5.5.4` when I tried 
```js
const { KafkaContainer } = require("testcontainers");

        const container = await new KafkaContainer(
            "confluentinc/cp-kafka:5.5.4", // Kafka image
            undefined, // Host
            "confluentinc/cp-zookeeper:5.5.4" // ZK image
        )
        .withExposedPorts(9093)
        .start();

**Comment by jonathankeebler** [comment]
Nevermind, I tried to pull the image manually and I was out of docker disk space. ☝️ works I think. Verifying I can connect...

**Comment by jonathankeebler** [comment]
Hardcoding v5.5.4 of the images resolves the issue. I would recommend hardcoding that version in your lib for the built-ins @cristianrgreco

**Comment by cristianrgreco** [comment]
I've raised a PR which sets the version to 5.5.4 by default, thanks @jonathankeebler. Is there anything else for this issue or can it be closed?
