### ISSUE TITLE
Unable to use container networking example in README

### ISSUE THREAD

**Issue by mmartinsky** [testcontainers/testcontainers-node#250]
I'm trying to network an express server container to another express server, but having difficulty running the networking example in the README. Created

s.js
```
const { GenericContainer, Network } = require('testcontainers');

async function f() {
    const network = await new Network().start();

    const container = await new GenericContainer('alpine:latest').withNetworkMode(network.getName()).start();

    const fooContainer = await new GenericContainer('alpine:latest')
        .withNetworkMode(network.getName())
        .withNetworkAliases('foo', 'bar')
        .start();

    const x = await container.exec(['nslookup', 'foo']);
    console.log({ x });
    await container.stop();
    await fooContainer.stop();
}

f();
```

as a test file, then ran `DEBUG=testcontainers node s.js`. It seems to fail on the exec for a stopped container:
```
bash $ DEBUG=testcontainers node s.js 
  testcontainers DEBUG Creating new Docker instance +0ms
  testcontainers DEBUG Creating new Reaper for session: 49bbd1941a67b880859e269d3bc4924d +51ms
  testcontainers INFO  Using default Docker host: localhost +4ms
  testcontainers DEBUG Executing Docker credential provider: docker-credential-desktop +3ms
  testcontainers DEBUG No credential found for registry: "https://index.docker.io/v1/" +79ms
  testcontainers DEBUG No registry auth locator found for registry: "https://index.docker.io/v1/" +1ms
  testcontainers DEBUG Not pulling image as it already exists: cristianrgreco/ryuk:0.4.0 +138ms
  testcontainers INFO  Creating container for image: cristianrgreco/ryuk:0.4.0 +6ms
  testcontainers INFO  Starting container cristianrgreco/ryuk:0.4.0 with ID: ad319077971daf56056ef9712c7579e633b94ae062ac4f8c441ccf359c16100c +66ms
  testcontainers DEBUG System diagnostics: {
  testcontainers   "node": {
  testcontainers     "version": "v12.18.0",
  testcontainers     "architecture": "x64",
  testcontainers     "platform": "darwin"
  testcontainers   },
  testcontainers   "docker": {
  testcontainers     "serverVersion": "20.10.2",
  testcontainers     "operatingSystem": "Docker Desktop",
  testcontainers     "operatingSystemType": "linux",
  testcontainers     "architecture": "x86_64",
  testcontainers     "cpus": 4,
  testcontainers     "memory": 2086899712
  testcontainers   },
  testcontainers   "dockerCompose": {
  testcontainers     "version": "1.27.4"
  testcontainers   }
  testcontainers } +363ms
  testcontainers DEBUG Waiting for container to be ready: ad319077971daf56056ef9712c7579e633b94ae062ac4f8c441ccf359c16100c +81ms
  testcontainers DEBUG Waiting for host port 11681 for ad319077971daf56056ef9712c7579e633b94ae062ac4f8c441ccf359c16100c +1ms
  testcontainers DEBUG Waiting for internal port 8080 for ad319077971daf56056ef9712c7579e633b94ae062ac4f8c441ccf359c16100c +1ms
  testcontainers DEBUG Host port 11681 ready for ad319077971daf56056ef9712c7579e633b94ae062ac4f8c441ccf359c16100c +4ms
  testcontainers DEBUG Internal port 8080 ready for ad319077971daf56056ef9712c7579e633b94ae062ac4f8c441ccf359c16100c +329ms
  testcontainers INFO  Container is ready +0ms
  testcontainers DEBUG Connecting to Reaper ad319077971daf56056ef9712c7579e633b94ae062ac4f8c441ccf359c16100c on localhost:11681 +0ms
  testcontainers DEBUG Connected to Reaper ad319077971daf56056ef9712c7579e633b94ae062ac4f8c441ccf359c16100c +1ms
  testcontainers INFO  Creating network d2dc280ab07177df639aa889613967a5 +1ms
  testcontainers INFO  Started network with ID: 5280318c4995842b86cc9e80dc0b2b1c7f31d7204c43793f9b882f5bfb3ce066 +117ms
  testcontainers DEBUG Executing Docker credential provider: docker-credential-desktop +1ms
  testcontainers DEBUG No credential found for registry: "https://index.docker.io/v1/" +93ms
  testcontainers DEBUG No registry auth locator found for registry: "https://index.docker.io/v1/" +2ms
  testcontainers DEBUG Not pulling image as it already exists: alpine:latest +207ms
  testcontainers INFO  Creating container for image: alpine:latest +0ms
  testcontainers INFO  Starting container alpine:latest with ID: 1c19e46316c69f34c00626f282eb0f6a275a5705066c86b389bdf915a343f33f +56ms
  testcontainers DEBUG Waiting for container to be ready: 1c19e46316c69f34c00626f282eb0f6a275a5705066c86b389bdf915a343f33f +510ms
  testcontainers INFO  Container is ready +0ms
  testcontainers DEBUG Executing Docker credential provider: docker-credential-desktop +0ms
  testcontainers DEBUG No credential found for registry: "https://index.docker.io/v1/" +69ms
  testcontainers DEBUG No registry auth locator found for registry: "https://index.docker.io/v1/" +0ms
  testcontainers DEBUG Not pulling image as it already exists: alpine:latest +140ms
  testcontainers INFO  Creating container for image: alpine:latest +0ms
  testcontainers INFO  Connecting container 5e34bfe5232d696bd2be8b5a9cb82767b41e5f4baf8b83fb5146546ddd005d0d to network d2dc280ab07177df639aa889613967a5 +47ms
  testcontainers INFO  Starting container alpine:latest with ID: 5e34bfe5232d696bd2be8b5a9cb82767b41e5f4baf8b83fb5146546ddd005d0d +8ms
  testcontainers DEBUG Waiting for container to be ready: 5e34bfe5232d696bd2be8b5a9cb82767b41e5f4baf8b83fb5146546ddd005d0d +558ms
  testcontainers INFO  Container is ready +0ms
  testcontainers ERROR Failed to exec container 1c19e46316c69f34c00626f282eb0f6a275a5705066c86b389bdf915a343f33f with command "nslookup foo": Error: (HTTP code 409) container stopped/paused - Container 1c19e46316c69f34c00626f282eb0f6a275a5705066c86b389bdf915a343f33f is not running  +5ms
(node:48129) UnhandledPromiseRejectionWarning: Error: (HTTP code 409) container stopped/paused - Container 1c19e46316c69f34c00626f282eb0f6a275a5705066c86b389bdf915a343f33f is not running 
    at MY_PATH/node_modules/docker-modem/lib/modem.js:315:17
    at getCause (MY_PATH/node_modules/docker-modem/lib/modem.js:345:7)
    at Modem.buildPayload (MY_PATH/node_modules/docker-modem/lib/modem.js:314:5)
    at IncomingMessage.<anonymous> (MY_PATH/node_modules/docker-modem/lib/modem.js:286:14)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:48129) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:48129) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
bash $ 
```

Is there something incorrect in my setup, or are the docs out of date?

**Comment by cristianrgreco** [comment]
The issue is that the alpine container will exit by default if not run in interactive mode. To keep the containers running I'd suggest adding something like `.withCmd(["top"])`, which will mean they are running when you run the nslookup command.

Thanks for raising @mmartinsky, I've updated the examples in the README.
