### ISSUE TITLE
Cannot run testcontainers

### ISSUE THREAD

**Issue by galah92** [testcontainers/testcontainers-node#391]
**Expected Behaviour**
The following should work:
```typescript
import { GenericContainer, StartedTestContainer } from "testcontainers";

let container: StartedTestContainer;

beforeAll(async () => {
  container = await new GenericContainer("postgres")
    .withExposedPorts(5432)
    .start();
});

afterAll(async () => {
  await container.stop();
});

test("create db", () => {
  console.log(container);
});
```

**Actual Behaviour**
```
 FAIL   test-postgres  packages/test-postgres/src/main.test.ts
  ● create db

    (HTTP code 500) container not running - Container c00a6417becbd8457f323a1b6659477b0ece390c5b743b3bdac4b64dd35df8f9 is not running: Exited (1) Less than a second ago

      at ../../node_modules/docker-modem/lib/modem.js:336:17
      at IncomingMessage.<anonymous> (../../node_modules/docker-modem/lib/modem.js:363:9)


  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'stop')

      10 |
      11 | afterAll(async () => {
    > 12 |   await container.stop();
         |                   ^
      13 | });
      14 |
      15 | test("create db", () => {

      at Object.<anonymous> (src/main.test.ts:12:19)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.779 s, estimated 3 s
Ran all test suites related to changed files.
```

**Steps to Reproduce**
1. Environment: NodeJS 16 over WSL2.

**Environment Information**
- Operating System: WSL2
- Docker Version: Docker version 20.10.17, build 100c701
- Node version: v16.15.1
- Testcontainers version: ^8.12.0

Would appreciate any help, thanks!

**Comment by cristianrgreco** [comment]
Failed to complete the issue template

**Comment by galah92** [comment]
@cristianrgreco can you explain what's missing?
