### ISSUE TITLE
Issue to fetch the image testcontainers/ryuk - Github action windows.

### ISSUE THREAD

**Issue by olivierodo** [testcontainers/testcontainers-node#413]
I'm not sure from where the issue is coming from...
I'm using GIthub action to run some unit test on my opensource project RestQA.
During the build we are performing the test on windows and Unix.
On Unix no issue at all,  however on windows i'm getting the error:
```
Error: (HTTP code 404) no such container - No such image: testcontainers/ryuk:0.3.2 
    at D:\a\restqa\restqa\node_modules\.pnpm\docker-modem@3.0.6\node_modules\docker-modem\lib\modem.js:336:17
    at getCause (D:\a\restqa\restqa\node_modules\.pnpm\docker-modem@3.0.6\node_modules\docker-modem\lib\modem.js:366:7)
    at Modem.buildPayload (D:\a\restqa\restqa\node_modules\.pnpm\docker-modem@3.0.6\node_modules\docker-modem\lib\modem.js:335:5)
    at IncomingMessage.<anonymous> (D:\a\restqa\restqa\node_modules\.pnpm\docker-modem@3.0.6\node_modules\docker-modem\lib\modem.js:303:16)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  reason: 'no such container',
  statusCode: 404,
  json: { message: 'No such image: testcontainers/ryuk:0.3.2' }
}
```
Result of the build: https://github.com/restqa/restqa/actions/runs/3548736493/jobs/5965213655
Issues open on RestQA: https://github.com/restqa/restqa/issues/268

**Comment by cristianrgreco** [comment]
Hi @olivierodo. Is your Windows agent configured to use Linux containers? What is the architecture of the agent? I am not sure it is an issue with testcontainers if the agent cannot find an image. I assume it'd be the same if you SSH'd onto the agent and tried to pull the image via the CLI.

**Comment by olivierodo** [comment]
Yes i think you are right that might not be a testcontainer issue, it might be related to the windows Github action agent.
The debugging experience is very poor on Github action,  so it's not very easy gather valuable information.

I'll share my findings on this issue.
