### ISSUE TITLE
How does this work with couchdb?

### ISSUE THREAD

**Issue by el-davo** [testcontainers/testcontainers-node#5]
Hi Im trying to get this to work with couchdb. However I keep getting an error. Here is my code

```
container = await new GenericContainer("couchdb")
            .withExposedPorts(5984)
            .start();
```

After running I get this error

```
 Error: Port :4369 not bound after 10000ms
      at retryStrategy.retryUntil (node_modules/testcontainers/dist/wait-strategy.js:59:23)
      at IntervalRetryStrategy.<anonymous> (node_modules/testcontainers/dist/retry-strategy.js:35:28)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/testcontainers/dist/retry-strategy.js:4:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
```

Not entirely sure where port `4369` is coming from. Perhaps I misunderstand the purpose of `withExposedPorts`.

I also noticed that it does seem to start the container correctly when I do a `docker ps` I can see the started container

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                         NAMES
a4722698ad61        couchdb:latest      "tini -- /docker-ent…"   13 seconds ago      Up 12 seconds       4369/tcp, 9100/tcp, 0.0.0.0:35121->5984/tcp   epic_raman

```

*UPDATE*

I also tried with a simple mysql container, And I get more or less the same error as above. Code below

```
container = await new GenericContainer("mysql")
            .withEnv("MYSQL_ROOT_PASSWORD", "my-secret-pw")
            .withExposedPorts(3306)
            .start();
```

And error

```
Error: Port :3306 not bound after 10000ms
      at retryStrategy.retryUntil (node_modules/testcontainers/dist/wait-strategy.js:59:23)
      at IntervalRetryStrategy.<anonymous> (node_modules/testcontainers/dist/retry-strategy.js:35:28)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/testcontainers/dist/retry-strategy.js:4:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
```

The only container that seems to work for me is the redis one in the main example on the readme

**Comment by cristianrgreco** [comment]
Hi @el-davo, thanks for flagging this. Could you share what version of node you're using?

**Comment by el-davo** [comment]
Hi @cristianrgreco I am on - v8.15.1

**Comment by el-davo** [comment]
Heres some debug info which may be helpful

```
 testcontainers Creating container for image: couchdb:latest +0ms
  testcontainers Starting container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +114ms
  testcontainers Waiting for host port :33831 +682ms
  testcontainers Waiting for internal port :4369 +4ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +2ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +518ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +491ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +473ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +525ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +476ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +531ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +514ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +548ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +523ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +476ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +481ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +514ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +3ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +485ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +495ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +3ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +531ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +529ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +2ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +521ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +496ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +497ms
  testcontainers Executing command "/bin/sh -c cat /proc/net/tcp6 | awk '{print $2}' | grep -i :1111" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c nc -vz -w 1 localhost 4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +1ms
  testcontainers Executing command "/bin/sh -c </dev/tcp/localhost/4369" on container with ID: eeca87d55439b34e418193c80acb544626403f862dc539dacf77cdf11a4e39dd +0ms

```

**Comment by encodeering** [comment]
Hey @el-davo, did you find a solution or way to handle this? I also ran into exactly this with a `mysql:5.6` container on `node v8.11.3` with `testcontainers 1.1.10`. 

Followed the example in the Readme and the code doesn't step over the `await ... start();` statement.

**Comment by cristianrgreco** [comment]
Hi @el-davo, @encodeering, I believe this has been fixed in version `1.1.11`.
Could you please upgrade and report back?

**Comment by cristianrgreco** [comment]
@el-davo, @encodeering I had some time this morning to verify that the change in `1.1.11` would fix CouchDB but it did not, meaning the issue for MySQL and CouchDB were different.

CouchDB should be fixed now in version `1.1.12`. 
Both MySQL and CouchDB are now tested in the build pipeline.

The two issues were as follows:
1. The port to hex conversion was not padded so when we checked the internal port to see if it was running we compared `:CEA` to `:0CEA` which meant that the port check would fail.
2. The old behaviour of the internal port check would gather all internal ports in the container and wait until they were all bound. For CouchDB, although you only care about `5984`, the port check was also waiting for `4369` as that's a port that the container exposes, but is never bound. Now we only wait for the ports you specify to be bound.

**Comment by encodeering** [comment]
Hi @cristianrgreco,

thanks for the update. just tried again with `1.1.14` and had no issues with mysql and sequelize.

do you think it would make sense to expose this kind of _health-check_ api to the container builder type? just in case when networking is not sufficient to consider a container _ready_.

**Comment by cristianrgreco** [comment]
@encodeering Great!

Yes it's something that needs to be done. We should provide different wait strategies and allow the user to choose. The network one is just a good default for now 🙂
