### ISSUE TITLE
Failed to connect to Reaper

### ISSUE THREAD

**Issue by nkyaw** [testcontainers/testcontainers-node#509]
**Expected Behaviour**
...Alpine container to be up and running.

**Actual Behaviour**
...Error occurred. 

**Testcontainer Logs**
 ```
npm start

> nodejs-test@1.0.0 start
> node src/testcontainers.js

Testing 1
ERROR Error: Failed to connect to Reaper fbb6f6502f7702587a1d65e4a40d1f4acd428ad198c0acf44da0aa239b92595f
    at /Users/nkyaw/Workspace/Source/test/nodejs-test/node_modules/testcontainers/dist/src/reaper.js:131:56
    at IntervalRetryStrategy.<anonymous> (/Users/nkyaw/Workspace/Source/test/nodejs-test/node_modules/testcontainers/dist/src/retry-strategy.js:37:28)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nkyaw/Workspace/Source/test/nodejs-test/node_modules/testcontainers/dist/src/retry-strategy.js:5:58)
```

**Steps to Reproduce**
1. In this environment...
2. With this config...
3. Run 
```
const { GenericContainer, Network } = require("testcontainers");

async function TestContainer() {
  try {
    console.log("Testing 1");
    const container = await new GenericContainer("alpine").start();
    console.log("Testing 2");
  } catch (e) {
    console.log("ERROR", e);
  }
}

TestContainer();
```
4. See error...

**Environment Information**
- Operating System: Mac
- Docker Version: 
  ``` docker version
  Client: Docker Engine - Community
   Version:           20.10.22
   API version:       1.41
   Go version:        go1.19.4
   Git commit:        3a2c30b63a
   Built:             Thu Dec 15 15:37:38 2022
   OS/Arch:           darwin/arm64
   Context:           default
   Experimental:      true
  
  Server: Docker Engine - Community
   Engine:
    Version:          20.10.23
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.18.10
    Git commit:       6051f14
    Built:            Thu Jan 19 17:34:42 2023
    OS/Arch:          linux/arm64
    Experimental:     false
   containerd:
    Version:          v1.6.15
    GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
   runc:
    Version:          1.1.4
    GitCommit:        5fd4c4d144137e991c4acebb2146ab1483a97925
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
  ```

- Node version: v18.14.0
- Testcontainers version: ^9.3.0

**Comment by cristianrgreco** [comment]
I will need to see all the logs, not just the error line

**Comment by cristianrgreco** [comment]
I will need to see all the logs, not just the error line (`DEBUG=testcontainers* npm ...`)

**Comment by rfoel** [comment]
I just had this error:
```
testcontainers [DEBUG] Found Docker client strategy "UnixSocketStrategy" +0ms
  testcontainers [DEBUG] Testing Docker client strategy "unix:///var/run/docker.sock"... +0ms
  testcontainers [DEBUG] Fetching system info... +22ms
  testcontainers [DEBUG] Node version: v18.16.0, Platform: darwin, Arch: arm64, OS: Docker Desktop, Version: 23.0.5, Arch: aarch64, CPUs: 4, Memory: 2085826560, Compose installed: true, Compose version: 2.17.3 +352ms
  testcontainers [INFO] Using Docker client strategy "UnixSocketStrategy", Docker host "localhost" (::1, 127.0.0.1) +2ms
  testcontainers [DEBUG] Not pulling image "amazon/dynamodb-local:latest" as it already exists +12ms
  testcontainers [DEBUG] Creating new Reaper for session "1cedf10f67e9"... +1ms
  testcontainers [DEBUG] Not pulling image "testcontainers/ryuk:0.4.0" as it already exists +5ms
  testcontainers [INFO] Creating container for image "testcontainers/ryuk:0.4.0"... +0ms
  testcontainers [INFO] [64c0b1ddb762] Created container for image "testcontainers/ryuk:0.4.0" +40ms
  testcontainers [INFO] [64c0b1ddb762] Starting container for image "testcontainers/ryuk:0.4.0"... +0ms
  testcontainers [INFO] [64c0b1ddb762] Started container for image "testcontainers/ryuk:0.4.0" +262ms
  testcontainers [DEBUG] [64c0b1ddb762] Waiting for container to be ready... +11ms
  testcontainers [DEBUG] [64c0b1ddb762] Waiting for log message "/.+ Started!/"... +0ms
  testcontainers:containers [64c0b1ddb762] 2023/05/09 11:58:35 Pinging Docker... +0ms
  testcontainers [INFO] [64c0b1ddb762] Container is ready +11ms
  testcontainers [DEBUG] [64c0b1ddb762] Connecting to Reaper (attempt 1) on "localhost:32768"... +0ms
  testcontainers:containers [64c0b1ddb762] 2023/05/09 11:58:35 Docker daemon is available! +8ms
  testcontainers:containers [64c0b1ddb762] 2023/05/09 11:58:35 Starting on port 8080... +0ms
  testcontainers:containers [64c0b1ddb762] 2023/05/09 11:58:35 Started! +0ms
  testcontainers [ERROR] Reaper 64c0b1ddb762274ec7c21e32cb4368ed85755f999e0a8bd149bdab4ce07d4891 socket error: Error: connect ECONNREFUSED ::1:32768 +4ms
  testcontainers [ERROR] [64c0b1ddb762] Connection to Reaper closed with error +1ms
  testcontainers [DEBUG] [64c0b1ddb762] Connecting to Reaper (attempt 2) on "localhost:32768"... +1s
  testcontainers [ERROR] Reaper 64c0b1ddb762274ec7c21e32cb4368ed85755f999e0a8bd149bdab4ce07d4891 socket error: Error: connect ECONNREFUSED ::1:32768 +2ms
  testcontainers [ERROR] [64c0b1ddb762] Connection to Reaper closed with error +0ms
  testcontainers [DEBUG] [64c0b1ddb762] Connecting to Reaper (attempt 3) on "localhost:32768"... +1s
  testcontainers [ERROR] Reaper 64c0b1ddb762274ec7c21e32cb4368ed85755f999e0a8bd149bdab4ce07d4891 socket error: Error: connect ECONNREFUSED ::1:32768 +1ms
  testcontainers [ERROR] [64c0b1ddb762] Connection to Reaper closed with error +1ms
  testcontainers [DEBUG] [64c0b1ddb762] Connecting to Reaper (attempt 4) on "localhost:32768"... +1s
  testcontainers [ERROR] Reaper 64c0b1ddb762274ec7c21e32cb4368ed85755f999e0a8bd149bdab4ce07d4891 socket error: Error: connect ECONNREFUSED ::1:32768 +2ms
  testcontainers [ERROR] [64c0b1ddb762] Connection to Reaper closed with error +1ms
  testcontainers [DEBUG] [64c0b1ddb762] Connecting to Reaper (attempt 5) on "localhost:32768"... +1s
  testcontainers [ERROR] Reaper 64c0b1ddb762274ec7c21e32cb4368ed85755f999e0a8bd149bdab4ce07d4891 socket error: Error: connect ECONNREFUSED ::1:32768 +2ms
  testcontainers [ERROR] [64c0b1ddb762] Connection to Reaper closed with error +0ms
  testcontainers [ERROR] [64c0b1ddb762] Failed to connect to Reaper +0ms
Error: Jest: Got error running globalSetup - /Users/rafael/Developer/finance/src/infra/test/setup/setup.js, reason: Failed to connect to Reaper
    at /Users/rafael/Developer/finance/node_modules/testcontainers/dist/src/reaper.js:134:24
    at IntervalRetryStrategy.<anonymous> (/Users/rafael/Developer/finance/node_modules/testcontainers/dist/src/retry-strategy.js:37:28)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/rafael/Developer/finance/node_modules/testcontainers/dist/src/retry-strategy.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by cristianrgreco** [comment]
Hi @rfoel, could you create a new issue?

**Comment by rfoel** [comment]
Sure!
