### ISSUE TITLE
Does not support Azure Container Registry

### ISSUE THREAD

**Issue by jinhong-** [testcontainers/testcontainers-node#579]
Looks like testcontainers is not compatible with ACR. It successfully picks up the credentials but would fail when trying to fetch the image

**Testcontainer Logs**
```
testcontainers [INFO] [646ea01cb1af] Container is ready +4s
  testcontainers [INFO] Pulling image "***.azurecr.io/***/***:latest"... +4ms
  testcontainers [DEBUG] Executing Docker credential provider "docker-credential-desktop" +0ms
  testcontainers [DEBUG] Auth config found for registry "***.azurecr.io": CredsStore +258ms
13:29:10.854 detox[1731] i Error: (HTTP code 500) server error - Head "***.azurecr.io/***/***:latest": unauthorized: aad access token with sp failed client id must be guid 
    at ***/node_modules/docker-modem/lib/modem.js:343:17
    at IncomingMessage.<anonymous> (***/node_modules/docker-modem/lib/modem.js:370:9)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  reason: 'server error',
  statusCode: 500,
  json: null
}
```

**Environment Information**
- Operating System: Intel MacOS 12
- Docker Version: 20.10.14
- Node version: v16.14.2
- Testcontainers version: 9.8.0

**Comment by jinhong-** [comment]
For anyone who faces this issue, it turns out that this is because the credential store does not store the username but converts it into `<token>`. I created a patch that replaces it with the correct username (which is a empty guid of 0s). this works for my use case but I am not sure what is the proper way to handle this

```
diff --git a/node_modules/testcontainers/dist/src/registry-auth-locator/credential-provider.js b/node_modules/testcontainers/dist/src/registry-auth-locator/credential-provider.js
index b322675..fa2b74c 100644
--- a/node_modules/testcontainers/dist/src/registry-auth-locator/credential-provider.js
+++ b/node_modules/testcontainers/dist/src/registry-auth-locator/credential-provider.js
@@ -29,7 +29,7 @@ class CredentialProvider {
             }
             const response = yield this.runCredentialProvider(registry, programName);
             return {
-                username: response.Username,
+                username: response.Username == '<token>' && registry?.endsWith('azurecr.io') ? '00000000-0000-0000-0000-000000000000' : response.Username,
                 password: response.Secret,
                 registryAddress: response.ServerURL,
             };
```

**Comment by cristianrgreco** [comment]
Hi @jinhong-, thanks for raising. Could you pls share a redacted example of what your `~/.docker/config.json` looks like? I have a local example that looks like this:

```json
{
    "auths": {
        "registry.azurecr.io": {
            "auth": "MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwOg==",
            "identitytoken": "REDACTED"
        }
    }
}
```

The decoded `auth` is `00000000-0000-0000-0000-000000000000:`.

I ask for an example from you because your patch is modifying the credential-provider, but I would've expected the change to be in the Auths class.

**Comment by cristianrgreco** [comment]
I've also been able to get a `~/.docker/config.json` structure similar to yours by using Docker Desktop, where the username is `<token>`, and there is no issue. I'm not sure why you say that a correct username is an empty guid of zeros. I will keep the issue open because I think there is an issue when not using a credential provider.

**Comment by cristianrgreco** [comment]
Both `~/.docker/config.json` structures work without issue for me, closing until I get more info/something reproducible.

**Comment by jinhong-** [comment]
Hi @cristianrgreco, apologies on not replying this. I am not able to provide the config.json because this is running in a github action runner, on a MacOS. There are some additional configurations that might be worth mentioning

1. I'm using azure managed identity credentials (machine to machine authentication), not the standard user credentials
2. I had to create a separate keychain so that the credentials can be stored and retrieved correctly. Here is the bash script i wrote to setup the keychain
```
          KEYCHAIN_PATH=$RUNNER_TEMP/cicd.keychain-db
          KEYCHAIN_PASSWORD=default
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security default-keychain -s $KEYCHAIN_PATH
```
3. I did not do the standard `az acr login --name <registry>` but used docker login instead after extracting the credentials (I recall az acr login did not work correctly). Below was how i fetched, then did docker login
```
          TOKEN=$(az acr login --name <registry> --expose-token --output tsv --query accessToken)
          docker login -h <remote host> <registry>.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password-stdin <<< $TOKEN
```
4. Because of the nature of the machine executing the scripts, it was unable to run docker locally, hence it was configured for remote docker via the follow environment variables
```
    TESTCONTAINERS_HOST_OVERRIDE: "<remote host>"
    DOCKER_HOST: tcp://<remote host>:2375
```
