### ISSUE TITLE
9.11.0 not starting with timezone-mock library

### ISSUE THREAD

**Issue by kristof-kasa** [testcontainers/testcontainers-node#618]
**Expected Behaviour**
Tests should start and finish successfully.

**Actual Behaviour**
The test hangs on the `Acquiring lock file` message and does not start.

**Testcontainer Logs**
```
  testcontainers [DEBUG] Testing Docker client strategy "UnixSocketStrategy" with URI "unix:///var/run/docker.sock"... +0ms
  testcontainers [DEBUG] Fetching system info... +116ms
  testcontainers [DEBUG] Node version: v18.15.0, Platform: darwin, Arch: arm64, OS: Docker Desktop, Version: 24.0.2, Arch: aarch64, CPUs: 4, Memory: 8232951808, Compose installed: true, Compose version: 2.19.1 +229ms
  testcontainers [DEBUG] Acquiring lock file "/var/folders/62/gjp5m07s2bd06jbtgkf12c5w0000gn/T/tc.lock"... +15ms
```

**Steps to Reproduce**

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

Example code:

example.test.js
```js
const tzMock = require('timezone-mock');
const { GenericContainer, Wait } = require('testcontainers');

jest.setTimeout(50000);

tzMock.register('UTC');

describe('Example', () => {
  let container1;

  beforeAll(async () => {
    container1 = await new GenericContainer('mongo:4.4')
      .withExposedPorts(27017)
      .withWaitStrategy(Wait.forLogMessage('Waiting for connections'))
      .start();

    console.log(container1.getMappedPort(27017), container2.getMappedPort(27017));
  })

  afterAll(async () => {
    await container1.stop({ timeout: 1000 });
  })

  it('should not fail', async () => {
    const host = container1.getHost();
    const port = container1.getMappedPort(27017);
    console.log(`mongodb://${host}:${port}`);

    expect(host).toBeDefined();
    expect(port).toBeDefined();
  })
});
```

package.json
```json
{
  "name": "testcontainers-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "NODE_ENV=test jest"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/jest": "^29.5.0",
    "jest": "^29.5.0",
    "mockdate": "^3.0.5",
    "testcontainers": "^9.11.0",
    "timezone-mock": "^1.3.6"
  }
}
```

Command:

```sh
$ DEBUG=testcontainers* npm run test
```

Result:

```sh
DEBUG=testcontainers* npm run test

> testcontainers-test@1.0.0 test
> NODE_ENV=test jest

  testcontainers [DEBUG] Testing Docker client strategy "UnixSocketStrategy" with URI "unix:///var/run/docker.sock"... +0ms
  testcontainers [DEBUG] Fetching system info... +17ms
  testcontainers [DEBUG] Node version: v18.15.0, Platform: darwin, Arch: arm64, OS: Docker Desktop, Version: 24.0.2, Arch: aarch64, CPUs: 4, Memory: 8232951808, Compose installed: true, Compose version: 2.19.1 +98ms
  testcontainers [DEBUG] Acquiring lock file "/var/folders/62/gjp5m07s2bd06jbtgkf12c5w0000gn/T/tc.lock"... +5ms
 FAIL  ./example.test.js (50.34 s)
  ● Example › should not fail

    thrown: "Exceeded timeout of 50000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

       9 |   let container1;
      10 |
    > 11 |   beforeAll(async () => {
         |   ^
      12 |     container1 = await new GenericContainer('mongo:4.4')
      13 |       .withExposedPorts(27017)
      14 |       .withWaitStrategy(Wait.forLogMessage('Waiting for connections'))

      at beforeAll (example.test.js:11:3)
      at Object.describe (example.test.js:8:1)


  ● Test suite failed to run

    TypeError: The "time" argument must be an instance of Date or an Time in seconds. Received an instance of MockDate

      at Object.probe (node_modules/proper-lockfile/lib/mtime-precision.js:22:8)
      at node_modules/proper-lockfile/lib/lockfile.js:33:35

  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'stop')

      19 |
      20 |   afterAll(async () => {
    > 21 |     await container1.stop({ timeout: 1000 });
         |                      ^
      22 |   })
      23 |
      24 |   it('should not fail', async () => {

      at Object.stop (example.test.js:21:22)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        50.359 s
Ran all test suites.
```

This happened when I upgraded from `9.1.1` to `9.11.0`

The problem is the [timezone-mock](https://www.npmjs.com/package/timezone-mock) library

**Environment Information**
- Operating System:  Mac OS 13.4
- Docker Version:  24.0.2
- Node version:  18.15.0
- Testcontainers version: 9.11.0

**Comment by cristianrgreco** [comment]
Hi @kristof-kasa, thanks for raising. I'm not sure what to do about this issue. 9.11.0 makes use of the [proper-lockfile](https://www.npmjs.com/package/proper-lockfile) library. If a dependency is mocking the runtime's datetime then it won't work as expected. Perhaps a simple solution would be to move `tzMock.register('UTC');` to after the container is started?

**Comment by kristof-kasa** [comment]
Hi @cristianrgreco 
That solves the issue; I don't know why I never thought about it. 🤦 

By the way, https://github.com/testcontainers/testcontainers-node/pull/597 (Create a single Reaper session per parallel test run) solved many of our CI/CD inconsistencies. It's a fantastic release so far. :) Thank you for the hard work!

**Comment by cristianrgreco** [comment]
> By the way, https://github.com/testcontainers/testcontainers-node/pull/597 (Create a single Reaper session per parallel test run) solved many of our CI/CD inconsistencies. It's a fantastic release so far

@kristof-kasa This makes me happy, thanks for the feedback! 😄
