### ISSUE TITLE
Unable to detect compiler type error on package installation on Windows 11 with VSCode

### ISSUE THREAD

**Issue by AxTrusov** [testcontainers/testcontainers-node#652]
**Expected Behaviour**
Running `yarn` succeeds without errors

**Actual Behaviour**
Running `yarn` fails with the following
```
PS C:\Projects\project-folder> yarn
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/3] ⡀ waiting...
[2/3] ⡀ cpu-features
warning Error running install script for optional dependency: "C:\\Projects\\project-folder\\node_modules\\cpu-features: Command failed.
Exit code: 1
Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
Arguments: 
Directory: C:\\Projects\\project-folder\\node_modules\\cpu-features
Output:
C:\\Projects\\project-folder\\node_modules\\buildcheck\\lib\\index.js:133
        throw new Error('Unable to detect compiler type');
        ^

Error: Unable to detect compiler type
    at new BuildEnvironment (C:\\Projects\\project-folder\\node_modules\\buildcheck\\lib\\index.js:133:15)
    at Object.<anonymous> (C:\\Projects\\project-folder\\node_modules\\cpu-features\\buildcheck.js:5:12)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Done in 44.88s.
```

**Testcontainer Logs**
Probably not relevant

**Steps to Reproduce**
1. Have a windows machine without regular Visual Studio installed (VSCode is the only IDE)
2. Try to run `yarn` on a project with `testcontainers`

**Environment Information**
- Operating System: Windows 11 Pro 22H2
- Docker Version: Docker version 20.10.22, build 3a2c30b
- Node version: v18.15.0
- Testcontainers version: 10.2.1

**Extra Details**
After digging into the error source code, it looks like `buildcheck` is not able to find any VisualStudio installations. I guess it looks for some sort of compiler that goes together with some of the versions. But if I don't have any regular Visual Studios installed and only using VSCode - is there any other pre-requisite that I can install?

**Comment by cristianrgreco** [comment]
Hi @AxTrusov, cpu-features is an optional dependency of ssh2, for this reason you can skip it:

```bash
npm install --omit=optional
```

**Comment by lijuchuan** [comment]
u not install docker,u can try install docker
