### ISSUE TITLE
Connection times out after spawning Docker

### ISSUE THREAD

**Issue by kpeters-cbsi** [testcontainers/testcontainers-node#73]
Using the following code I am unable to connect to the spawned Docker. Is there something I'm doing wrong?

```
const { createPool } = require('mysql2/promise')
const { GenericContainer, Wait } = require('testcontainers')
const mysqlContainer = async () => {
  const container = await new GenericContainer('mysql', '5.7')
    .withExposedPorts(3306)
    .withEnv('MYSQL_ALLOW_EMPTY_PASSWORD', '1')
    .withEnv('MYSQL_DATABASE', 'testdb')
    .withWaitStrategy(Wait.forLogMessage('mysqld: ready for connections.'))
    .start()
  console.log('Container started')
  return container
}

(async () => {
  const container = await mysqlContainer()
  try {
    const connection = await createPool({ host: 'localhost', user: 'root', password: '', port: container.getMappedPort(3306) })
    console.log('Connected to database')
    console.log(await (connection.query('SELECT count(*) FROM information_schema.columns')))
  } catch (e) {
    console.error(e, e.stack)
  }
  await container.stop()
})()
```

**Comment by cristianrgreco** [comment]
Hi @kpeters-cbsi 

Could you please share any log output/errors with `DEBUG=testcontainers` enabled?

The host may not be `localhost`, I'd advise setting it to `container.getContainerIpAddress()`.

**Comment by kpeters-cbsi** [comment]
See below. I've changed the host to `container.getContainerIpAddress()`; that did not fix matters.

```
DEBUG=testcontainers node ~/work/sketches/mysqldocker/index.js 
  testcontainers INFO: Using Docker defaults +0ms
  testcontainers INFO: Creating container for image: mysql:5.7 +37ms
  testcontainers INFO: Starting container with ID: 47e1d348e751f4da0e6af57b5f14621d31a353e5c51a5e4aaa38dd9dd7271fa2 +48ms
  testcontainers DEBUG: Waiting for container to be ready +459ms
  testcontainers DEBUG: Waiting for log message "mysqld: ready for connections." +0ms
  testcontainers DEBUG: Container is ready +5s
Container started
Connected to database
Error: Connection lost: The server closed the connection.
    at PromisePool.query (/home/kit/work/sketches/mysqldocker/node_modules/mysql2/promise.js:330:22)
    at /home/kit/work/sketches/mysqldocker/index.js:19:35
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  message: 'Connection lost: The server closed the connection.',
  code: 'PROTOCOL_CONNECTION_LOST',
  errno: undefined,
  sqlState: undefined,
  sqlMessage: undefined
} Error: Connection lost: The server closed the connection.
    at PromisePool.query (/home/kit/work/sketches/mysqldocker/node_modules/mysql2/promise.js:330:22)
    at /home/kit/work/sketches/mysqldocker/index.js:19:35
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT
    at PoolConnection._handleTimeoutError (/home/kit/work/sketches/mysqldocker/node_modules/mysql2/lib/connection.js:178:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Emitted 'error' event on PoolConnection instance at:
    at PoolConnection._notifyError (/home/kit/work/sketches/mysqldocker/node_modules/mysql2/lib/connection.js:221:12)
    at PoolConnection._handleFatalError (/home/kit/work/sketches/mysqldocker/node_modules/mysql2/lib/connection.js:156:10)
    at PoolConnection._handleNetworkError (/home/kit/work/sketches/mysqldocker/node_modules/mysql2/lib/connection.js:169:10)
    at PoolConnection._handleTimeoutError (/home/kit/work/sketches/mysqldocker/node_modules/mysql2/lib/connection.js:182:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  fatal: true
}
```

**Comment by cristianrgreco** [comment]
I've just noticed that the mysql container logs log the message "mysqld: ready for connections." twice. It immediately shuts down after the first log, I assume that's the issue.

```
...
2020-04-29T16:57:13.626915Z 0 [Note] Event Scheduler: Loaded 0 events
2020-04-29T16:57:13.627468Z 0 [Note] mysqld: ready for connections.
Version: '5.7.30'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
2020-04-29 16:57:14+00:00 [Note] [Entrypoint]: Temporary server started.
...
2020-04-29 16:57:18+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
...
2020-04-29T16:57:19.148905Z 0 [Note] Event Scheduler: Loaded 0 events
2020-04-29T16:57:19.149436Z 0 [Note] mysqld: ready for connections.
```

**Comment by kpeters-cbsi** [comment]
Is that something I'm doing on my end?

**Comment by kpeters-cbsi** [comment]
Taking out `.withWaitStrategy(Wait.forLogMessage('mysqld: ready for connections.'))` seems to have corrected the issue. I have no idea why, though.

**Comment by kpeters-cbsi** [comment]
Updated sketch:

```
const { createPool } = require('mysql2/promise')
const { GenericContainer, Wait } = require('testcontainers')
const mysqlContainer = async () => {
  const container = await new GenericContainer('mysql', '5.7')
    .withExposedPorts(3306)
    .withEnv('MYSQL_ALLOW_EMPTY_PASSWORD', '1')
    .withEnv('MYSQL_DATABASE', 'testdb')
    .start()
  console.log('Container started')
  return container
}

(async () => {
  const container = await mysqlContainer()
  try {
    const connection = await createPool({ host: container.getContainerIpAddress(), user: 'root', password: '', port: container.getMappedPort(3306) })
    console.log('Connected to database')
    console.log(await (connection.query('SELECT count(*) FROM information_schema.columns')))
  } catch (e) {
    console.error(e, e.stack)
  }
  await container.stop()
})()
```

**Comment by cristianrgreco** [comment]
@kpeters-cbsi The WaitStrategy was set to pass when the container output `mysqld: ready for connections`, you can see from my previous reply that the mysql container will log that, and then immediately shut down and start up again, this is part of its initialisation process. Testcontainers would see the first message and think it's ready, but then the container would shut down.

By removing the `withWaitStrategy`, testcontainers will instead wait for the port to be bound, which happens when mysql has completed initialisation.

**Comment by kpeters-cbsi** [comment]
Thanks for your help. Feel free to use this as an example if you think it would be helpful.
