### ISSUE TITLE
Running container with Deno raises exception due to unimplemented method

### ISSUE THREAD

**Issue by totto2727** [testcontainers/testcontainers-node#753]
**Expected Behaviour**

- Unimplemented methods will not be executed
- Containers are executed as appropriate

**Actual Behaviour**

- Unimplemented methods will not be executed
- Containers are executed as appropriate

**Testcontainer Logs**

```
error: Uncaught (in promise) TypeError: stream.socket.unref is not a function
    at DockerContainerClient.logs (file:///Users/h_tsuchida/Library/Caches/deno/npm/registry.npmjs.org/testcontainers/10.8.1/build/container-runtime/clients/container/docker-container-client.js:165:27)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async LogWaitStrategy.waitUntilReady (file:///Users/h_tsuchida/Library/Caches/deno/npm/registry.npmjs.org/testcontainers/10.8.1/build/wait-strategies/log-wait-strategy.js:22:24)
    at async waitForContainer (file:///Users/h_tsuchida/Library/Caches/deno/npm/registry.npmjs.org/testcontainers/10.8.1/build/wait-strategies/wait-for-container.js:8:9)
    at async GenericContainer.startContainer (file:///Users/h_tsuchida/Library/Caches/deno/npm/registry.npmjs.org/testcontainers/10.8.1/build/generic-container/generic-container.js:140:9)
    at async createNewReaper (file:///Users/h_tsuchida/Library/Caches/deno/npm/registry.npmjs.org/testcontainers/10.8.1/build/reaper/reaper.js:59:30)
    at async file:///Users/h_tsuchida/Library/Caches/deno/npm/registry.npmjs.org/testcontainers/10.8.1/build/reaper/reaper.js:26:20
    at async withFileLock (file:///Users/h_tsuchida/Library/Caches/deno/npm/registry.npmjs.org/testcontainers/10.8.1/build/common/file-lock.js:41:16)
    at async getReaper (file:///Users/h_tsuchida/Library/Caches/deno/npm/registry.npmjs.org/testcontainers/10.8.1/build/reaper/reaper.js:16:14)
    at async PostgreSqlContainer.start (file:///Users/h_tsuchida/Library/Caches/deno/npm/registry.npmjs.org/testcontainers/10.8.1/build/generic-container/generic-container.js:72:28)
```

**Steps to Reproduce**
1. Create main.ts
    ```ts
    import { PostgreSqlContainer } from "npm:@testcontainers/postgresql"

    const postgresContainer = await new PostgreSqlContainer()
      .withExposedPorts(5432)
      .withCopyDirectoriesToContainer([
        { source: "./migration", target: "/docker-entrypoint-initdb.d" },
      ])
      .start()

    await postgresContainer.stop()
    ```
2. Execute main.ts
    ```bash
    deno run --allow-all main.ts
    ```

**Environment Information**
- Operating System: `macOS Sonoma 14.3.1`
- Docker Version: `Docker version 26.0.0, build 2ae903e86c`（Orbstack）
- Testcontainers version: `10.8.1`
- Deno Version: `deno 1.42.0 (release, aarch64-apple-darwin) v8 12.3.219.9 typescript 5.4.3`

**supplement**

If you comment out the following line, or verify that the `unref()` method exists before executing it (`stream.socket.unref && stream.socket.unref();`), this exception will not be raised and the container will be successfully launched.

[stream.socket.unref();](https://github.com/testcontainers/testcontainers-node/blob/e56ec2bf8d8c04ccc0ff671d920d666603ed6e64/packages/testcontainers/src/container-runtime/clients/container/docker-container-client.ts#L168)

When I checked the value of stream.socket in console.log, the following log was returned.

```
stream FakeSocket {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  remoteAddress: undefined,
  remotePort: undefined,
  encrypted: undefined,
  writable: true,
  readable: true,
  [Symbol(kCapture)]: false
}
```

It seems to be due to the fact that the `unref()` method is not implemented in this `FakeSocket` class.

https://github.com/denoland/deno/blob/2ec366f54423dc577379b9245e498681fccf3050/ext/node/polyfills/http.ts#L273

I cannot determine if it is correct in itself that a FakerSocket instance is returned in the Deno environment...
I would be happy if you could give me some hints.

I understand that Deno is not officially supported, but I would appreciate your support.

**Comment by cristianrgreco** [comment]
Hi @totto2727, there's not much I can do here. It's crucial to unref the socket otherwise the app process won't terminate so long as the container is running. So checking if it's defined before invoking it as suggested will just result in other issues. Sounds like you did the right thing raising then issue with demo.
