### ISSUE TITLE
Couchbase Initialization Not Working

### ISSUE THREAD

**Issue by joeyagreco** [testcontainers/testcontainers-node#826]
**Expected Behaviour**
Able to initialize Couchbase as shown in examples
- [Example 1](https://testcontainers.com/modules/couchbase/)
- [Example 2](https://node.testcontainers.org/modules/couchbase/)
___
**Actual Behaviour**
1. Imports needed are not available. [These are the only available imports](https://github.com/testcontainers/testcontainers-node/blob/main/packages/modules/couchbase/src/index.ts), which makes the examples and tests shown [here](https://node.testcontainers.org/modules/couchbase/) and [here](https://github.com/testcontainers/testcontainers-node/blob/9f7fd4eff5e6f05440016010964a78aa80557cb1/packages/modules/couchbase/src/couchbase-container.test.ts) not accessable for users.
2. Get strange error when trying to initialize a test container: `Cannot find module 'testcontainers/src/utils/bound-ports`
___
**Testcontainer Logs**
```
> npx jest issue.test.ts
 FAIL  src/issue.test.ts
  ● Test suite failed to run

    Cannot find module 'testcontainers/src/utils/bound-ports' from '../../../node_modules/.pnpm/@testcontainers+couchbase@10.12.0/node_modules/@testcontainers/couchbase/build/couchbase-container.js'

    Require stack:
      /Users/joeygreco/my_repo/node_modules/.pnpm/@testcontainers+couchbase@10.12.0/node_modules/@testcontainers/couchbase/build/couchbase-container.js
      /Users/joeygreco/my_repo/node_modules/.pnpm/@testcontainers+couchbase@10.12.0/node_modules/@testcontainers/couchbase/build/index.js
      src/issue.test.ts

    > 1 | import { CouchbaseContainer, StartedCouchbaseContainer } from '@testcontainers/couchbase';
        | ^
      2 |
      3 | let startedTestContainer;
      4 |

      at Resolver._throwModNotFoundError (../../../node_modules/.pnpm/jest-resolve@29.7.0/node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (../../../node_modules/.pnpm/@testcontainers+couchbase@10.12.0/node_modules/@testcontainers/couchbase/src/couchbase-container.ts:10:1)
      at Object.<anonymous> (../../../node_modules/.pnpm/@testcontainers+couchbase@10.12.0/node_modules/@testcontainers/couchbase/src/index.ts:1:1)
      at Object.<anonymous> (src/issue.test.ts:1:1)
```
___
**Steps to Reproduce**
Here's a basic Jest test that will fail with the above error:

```ts
import { CouchbaseContainer } from '@testcontainers/couchbase';

describe('test connection', () => {
  test('success', async () => {
    // usage shown in example here: https://testcontainers.com/modules/couchbase/
    const container1 = await new CouchbaseContainer().start();
  });
});
```
Additionally, these imports are not exported in the `@testcontainers/couchbase` npm package:
```ts
import { BucketDefinition } from "./bucket-definition";
import { CouchbaseService } from "./couchbase-service";
```
___
**Environment Information**
- Operating System: MacOS
- Docker Version: Docker version 27.1.1, build 6312585
- Node version: v20.16.0
- Testcontainers version:  @testcontainers/couchbase@10.12.0

Thanks!

**Comment by cristianrgreco** [comment]
Good point. Looks like the Couchbase module isn't setup correctly. PR welcome

**Comment by cristianrgreco** [comment]
Update:

> Get strange error when trying to initialize a test container: Cannot find module 'testcontainers/src/utils/bound-ports

This has been resolved in 10.19.0. 

> Imports needed are not available. These are the only available imports, which makes the examples and tests shown here and here not accessible for users.

Just need to add some more exports to https://github.com/testcontainers/testcontainers-node/blob/main/packages/modules/couchbase/src/index.ts. PR welcome.
